project:
  type: website
  output-dir: docs

website:
  title: "fishR"
  favicon: /img/fishRlogo_Tight_Dark_trans.png
  site-url: https://fishr-core-team.github.io/fishR/
  navbar:
    title: false
    logo: /img/fishRlogo_Tight_Light_trans.png
    left:
      - text: Examples
        href: blog/index.qmd
      - text: Books
        href: books.qmd
      - text: Packages
        href: packages.qmd
      - text: Data
        menu: 
          - text: "fishR (alphabetical)"
            file: data_fishR_alpha.qmd
          - text: "fishR (by topic)"
            file: data_fishR_byTopic.qmd
          - text: "Comprehensive (by package)"
            file: data_Comp_byPackage.qmd
          - text: "Comprehensive (by topic)"
            file: data_Comp_byTopic.qmd
    pinned: true
  page-footer:
    left: 
      - text: "fishR Core Team"
        href: https://github.com/fishR-Core-Team
    background: primary
  repo-url: https://fishr-core-team.github.io/fishR
  repo-actions: [edit, issue]
  open-graph: true
  reader-mode: true
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    smooth-scroll: true
execute: 
  freeze: auto
