project:
  type: website
  output-dir: docs

website:
  title: "fishR"
  favicon: /img/fishRlogo_Tight_Dark_trans.png
  site-url: https://fishr-core-team.github.io/fishR/
  repo-url: https://fishr-core-team.github.io/fishR
  repo-actions: [edit, issue]
  navbar:
    title: false
    logo: /img/fishRlogo_Tight_Light_trans.png
    background: primary
    left:
      - text: Posts
        href: blog/index.qmd
      - text: Books
        href: pages/books.qmd
      - text: Packages
        href: pages/packages.qmd
      - text: Data
        menu: 
          - text: "fishR (alphabetical)"
            file: pages/data_fishR_alpha.qmd
          - text: "fishR (by topic)"
            file: pages/data_fishR_byTopic.qmd
          - text: "Comprehensive (by package)"
            file: pages/data_Comp_byPackage.qmd
          - text: "Comprehensive (by topic)"
            file: pages/data_Comp_byTopic.qmd
    pinned: true
  page-footer:
    left: 
      - text: "fishR Core Team"
        href: https://github.com/fishR-Core-Team
    background: primary
  comments:
    giscus:
      repo: fishR-Core-Team/fishR
      loading: lazy
      theme: preferred_color_scheme
  open-graph: true
format:
  html:
    theme: 
      light: [flatly, css/light.scss]
      dark: [darkly, css/dark.scss]
    css: css/styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    smooth-scroll: true
    title-block-banner: true
highlight-style: github
date-format: medium
execute: 
  freeze: auto
