{
  "hash": "5e9e20a1d3c53e3c0c8e1c17410a5d17",
  "result": {
    "markdown": "---\ntitle: Miller et al. (2022) Catch Curve Plot\ndescription: Using ggplot2 to recreate the catch curve plot in Miller et al. (2022).\nauthor: Derek H. Ogle\ndate: 4/1/2023\nimage: preview.png\ncategories:\n  - Mortality\n  - Catch Curve\n  - ggplot2\n  - line plot\n  - regression\n  - labels\n---\n\n\n:::{.callout-important}\n## Series Note\nThis is the third and last post related to @milleretal_2022. I do not have plans to recreate their Figure 5 as it looks like they largely followed [this post](../2019-12-31_vonB_plots_1/).\n:::\n\n# Introduction\n@milleretal_2022 examined life history characteristics of Goldeye (*Hiodon alosoides*) in two Kansas reservoirs. Their [Figure 4](https://meridian.allenpress.com/view-large/figure/14538582/i1944-687X-13-1-243-f04.tif) represents a catch curve (log catch at age) for Goldeye captured in Milford Reservoir in 2020. I use `FSA` and `ggplot2` here to recreate this figure.\n\nThe following packages are loaded for use below. A few functions from each of `readxl` and `scales` are used with `::` such that the entire packages are not attached here.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)  # for dplyr, ggplot2 packages\nlibrary(ggtext)     # for use of markdown in text/labels\nlibrary(FSA)        # for catchCurve et al.\n```\n:::\n\n\n&nbsp;\n\n# Data Wrangling\n@milleretal_2022 provided the raw data for producing Figure 4 in their Data Supplement S2. These are the same data used to recreate Figures 2 and 3 [in this post](../2023-3-31_Milleretal2022_Fig23/). Thus, I do not explain the data wrangling used to obtain `dat2` below.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndat2 <- read.csv(\"../2023-3-31_Milleretal2022_Fig23/JFWM-21-090.S2.csv\") |>\n  filter(ann==1)\nhead(dat2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.output}\n#R|    netid  tl   w agecap ann bclen\n#R|  1     6 385 521      6   1   210\n#R|  2     6 357 466      4   1   213\n#R|  3     6 397 725      5   1   209\n#R|  4     8 393 610      8   1   202\n#R|  5     8 373 571      4   1   193\n#R|  6     8 389 656      6   1   163\n```\n:::\n:::\n\n\nThe total catch of individuals at each age-at-capture is required to construct Figure 4. One issue that occurs with these data is that no age-2 fish were captured and @milleretal_2022 treat this as an observed zero. If the data are simply grouped by `agecap` and summarized then no age-2 data will be present in the result. There are several ways to deal with this but I am going to handle it by first creating a new variable `fagecap` that is a factored version of `agecap`. The key here, though, is to set the levels of this new variable to cover the entire range of observed ages.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndat2 <- dat2 |>\n  mutate(fagecap=factor(agecap,levels=1:8))\n```\n:::\n\n\nThe \"sample size\" (i.e., catch) at each `fagecap` is then found. It is important to use `.drop=FALSE` so that the age-2 \"level\" is not removed from the resultant data frame because it did not exist in the original data frame.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsum_a <- dat2 |>\n  group_by(fagecap,.drop=FALSE) |>\n  summarize(catch=n())\nsum_a\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.output}\n#R|  # A tibble: 8 × 2\n#R|    fagecap catch\n#R|    <fct>   <int>\n#R|  1 1         122\n#R|  2 2           0\n#R|  3 3           5\n#R|  4 4           7\n#R|  5 5          10\n#R|  6 6           3\n#R|  7 7           2\n#R|  8 8           3\n```\n:::\n:::\n\n\nThe issue now with using these data is that `fcapage` is a factor rather than a numeric. Thus, a new `agecap` variable is created below that treats age as numeric.^[This conversion code comes from `?factor`.]\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsum_a <- sum_a |>\n  mutate(agecap=as.numeric(levels(fagecap)))\nsum_a\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.output}\n#R|  # A tibble: 8 × 3\n#R|    fagecap catch agecap\n#R|    <fct>   <int>  <dbl>\n#R|  1 1         122      1\n#R|  2 2           0      2\n#R|  3 3           5      3\n#R|  4 4           7      4\n#R|  5 5          10      5\n#R|  6 6           3      6\n#R|  7 7           2      7\n#R|  8 8           3      8\n```\n:::\n:::\n\n\nFinally, the catch curve analysis ultimately requires log-transforming the catch variable. The zero for age-2 will cause an error when log-transforming. The authors addressed this by adding 1 to all of the `catch`es. This is common practice, but I comment on it further below. Also, for use when recreating Figure 4, the log of these modified catches are added to the data frame.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsum_a <- sum_a |>\n  mutate(catch1=catch+1,\n         logcatch1=log(catch1))\nsum_a\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.output}\n#R|  # A tibble: 8 × 5\n#R|    fagecap catch agecap catch1 logcatch1\n#R|    <fct>   <int>  <dbl>  <dbl>     <dbl>\n#R|  1 1         122      1    123      4.81\n#R|  2 2           0      2      1      0   \n#R|  3 3           5      3      6      1.79\n#R|  4 4           7      4      8      2.08\n#R|  5 5          10      5     11      2.40\n#R|  6 6           3      6      4      1.39\n#R|  7 7           2      7      3      1.10\n#R|  8 8           3      8      4      1.39\n```\n:::\n:::\n\n\n# Catch Curve Analysis\nCatch curves analysis^[I assume the reader is familiar with catch curves. If not see Chapter 11 in @ogleIntroductoryFisheriesAnalyses2016.] may be conducted with `catchCurve()` from `FSA`. `catchCurve` require a formula of the form `catch~age` as the first argument and the corresponding data frame in `data=`. The \"weighted catch curve\" that @milleretal_2022 used requires `weighted=TRUE` in `catchCurve()`. The results should be saved to an object.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncc1 <- catchCurve(catch1~agecap,data=sum_a,weighted=TRUE)\n```\n:::\n\n\nThe point estimates of $Z$ and $A$ may be extracted with `coef()` or seen in the `Estimate` column of the `summary()` results.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncoef(cc1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.output}\n#R|           Z          A \n#R|   0.2709483 23.7344113\n```\n:::\n\n```{.r .cell-code}\nsummary(cc1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.output}\n#R|      Estimate Std. Error  t value  Pr(>|t|)\n#R|  Z  0.2709483  0.2544583 1.064805 0.3279271\n#R|  A 23.7344113         NA       NA        NA\n```\n:::\n:::\n\n\nThe so-called \"recruitment coefficient of determination\" (RCD) in @milleretal_2022 is just the usual r<sup>2</sup>, which can be extracted from the `summary()` of the `lm` object in `cc1`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n( r2 <- summary(cc1$lm)$r.squared )\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.output}\n#R|  [1] 0.1589346\n```\n:::\n:::\n\n\nThese results were put into a label that will ultimately be placed on the plot.^[This process is discussed in several previous posts, including [this one](../2023-3-29_Milleretal2022_Fig1/#reservoir-and-regression-result-labels).]\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlbl <- paste0(\"*Z* = \",round(coef(cc1)[[\"Z\"]],2),\n              \"<br>*A* = \",round(coef(cc1)[[\"A\"]],2),\"%\",\n              \"<br>RCD = \",round(r2,2))\nlbl\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.output}\n#R|  [1] \"*Z* = 0.27<br>*A* = 23.73%<br>RCD = 0.16\"\n```\n:::\n:::\n\n\nThe `cc1` object also contains the data used in the catch curve analysis, including the weights in an object called `weights.e`. These weights are added to the `sum_a` data frame as they are needed to produce Figure 4.^[The weights can be produced \"manually\" as described in @ogleIntroductoryFisheriesAnalyses2016, but this process using `catchCurve()` is more efficient and less prone to error.]\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsum_a <- sum_a |>\n  mutate(wts=cc1$weights.e)\nsum_a\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.output}\n#R|  # A tibble: 8 × 6\n#R|    fagecap catch agecap catch1 logcatch1   wts\n#R|    <fct>   <int>  <dbl>  <dbl>     <dbl> <dbl>\n#R|  1 1         122      1    123      4.81  2.68\n#R|  2 2           0      2      1      0     2.45\n#R|  3 3           5      3      6      1.79  2.22\n#R|  4 4           7      4      8      2.08  1.98\n#R|  5 5          10      5     11      2.40  1.75\n#R|  6 6           3      6      4      1.39  1.52\n#R|  7 7           2      7      3      1.10  1.29\n#R|  8 8           3      8      4      1.39  1.06\n```\n:::\n:::\n\n\nThe data in `sum_a` are now ready to recreate Figure 4.\n\n&nbsp;\n\n# Recreating Figure 4\nFigure 4 is simply a scatterplot with a regression line overlaid. Constructing these kinds of plots was discussed in detail in [this post](../2023-3-31_Milleretal2022_Fig23/#recreating-figure-3). Thus, most of the code below are not discussed in depth. A very important detail, though, is that mapping `weight=wts` will provide the `wts` to `lm()` in `geom_smooth()` as weights, so that the weighted regression is used in the same way as was done in `catch_curve()`.^[In my opinion, the y-axis title should clearly note that 1 was added to the catches. Thus, my y-axis title is different than that in @milleretal_2022.] \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data=sum_a,mapping=aes(x=agecap,y=logcatch1,weight=wts)) +\n  geom_smooth(method=\"lm\",se=FALSE,color=\"black\") +\n  geom_point() +\n  scale_x_continuous(name=\"Estimated age\",\n                     limits=c(0,8),breaks=scales::breaks_width(1),\n                     expand=expansion(mult=c(0,0.02))) +\n  scale_y_continuous(name=\"log(catch+1)\",\n                     limits=c(0,5),breaks=scales::breaks_width(1),\n                     expand=expansion(mult=c(0.01,0))) +\n  theme_bw() +\n  theme(panel.grid=element_blank(),\n        axis.title=element_text(size=12,face=\"bold\"),\n        axis.text=element_text(size=10,face=\"bold\",color=\"black\")) +\n  annotate(geom=\"richtext\",x=Inf,y=Inf,vjust=1,hjust=1,label=lbl,\n           label.color=NA,fontface=\"bold\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/make-fig4-1.png){fig-align='center' width=480}\n:::\n:::\n\n\n### Possible Modifications\nAs with other posts related to @milleretal_2022, a confidence band can be added to this regression.^[Note use of `coord_cartesian()` as the confidence band extends outside the desired range of the y-axis.]\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data=sum_a,mapping=aes(x=agecap,y=logcatch1,weight=wts)) +\n  geom_smooth(method=\"lm\",color=\"black\") +\n  geom_point() +\n  scale_x_continuous(name=\"Estimated age\",\n                     limits=c(0,8),breaks=scales::breaks_width(1),\n                     expand=expansion(mult=c(0,0.02))) +\n  scale_y_continuous(name=\"log(catch+1)\",\n                     breaks=scales::breaks_width(1),\n                     expand=expansion(mult=c(0.01,0))) +\n  coord_cartesian(ylim=c(0,5)) +\n  theme_bw() +\n  theme(panel.grid=element_blank(),\n        axis.title=element_text(size=12,face=\"bold\"),\n        axis.text=element_text(size=10,face=\"bold\",color=\"black\")) +\n  annotate(geom=\"richtext\",x=Inf,y=Inf,vjust=1,hjust=1,label=lbl,\n           label.color=NA,fontface=\"bold\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/make-fig4-alt-1.png){fig-align='center' width=480}\n:::\n:::\n\n\nHere, I think the confidence band is critical to include because it demonstrates that the regression line is NOT statistically declining.^[This was also apparent by the \"large\" p-value for the slope in the `summary(cc1)` results above.] Obviously, there is mortality in this population, so this indicates data issues.\n\nA major assumption of catch curve analysis is that recruitment is constant, which it clearly is not here. The most glaring evidence of this is the complete lack of age-2 fish. I don't know if the age-2 fish should be considered as an observed zero (i.e., that age-class is actually very low) or if there is a sampling issue (i.e., was the gear highly selective; here is some evidence for that in the length frequency histogram in their Figure 2 and in [this post](../2023-3-31_Milleretal2022_Fig23/#recreating-figure-2).)\n\nIt is common to add 1 to \"integer\" data that has zeroes prior to log-transformation. However, this can be problematic. For example, adding 1 to the catch of age-1 fish is relatively minor (<1% change from 122 to 123), but the same modification is relatively important for the catch of age-7 fish (50% increase from 2 to 3). This can influence mortality estimates. For example, below one was added **only** to the age-2 catch.^[I am not suggesting that this is the correct thing to do. However, the authors would not have added a 1 if *one* age-2 fish had been captured. Thus, this will demonstrate some level of sensitivity to the data collection and analysis choice.]\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsum_a <- sum_a |>\n  mutate(catch1a=ifelse(agecap==2,1,catch))\nsum_a\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.output}\n#R|  # A tibble: 8 × 7\n#R|    fagecap catch agecap catch1 logcatch1   wts catch1a\n#R|    <fct>   <int>  <dbl>  <dbl>     <dbl> <dbl>   <dbl>\n#R|  1 1         122      1    123      4.81  2.68     122\n#R|  2 2           0      2      1      0     2.45       1\n#R|  3 3           5      3      6      1.79  2.22       5\n#R|  4 4           7      4      8      2.08  1.98       7\n#R|  5 5          10      5     11      2.40  1.75      10\n#R|  6 6           3      6      4      1.39  1.52       3\n#R|  7 7           2      7      3      1.10  1.29       2\n#R|  8 8           3      8      4      1.39  1.06       3\n```\n:::\n:::\n\n\nAnd the catch curve analysis was conducted with these data instead.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncc1a <- FSA::catchCurve(catch1a~agecap,data=sum_a,weighted=TRUE)\nsummary(cc1a)\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.output}\n#R|      Estimate Std. Error  t value  Pr(>|t|)\n#R|  Z  0.3400406  0.2737122 1.242329 0.2604674\n#R|  A 28.8258572         NA       NA        NA\n```\n:::\n:::\n\n\nThe issue of no statistical decline is still evident, but the point estimates of A, for example, has increased substantially.\n\nIgnoring the age-2 \"fish\" completely has an even larger effect.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncc1b <- FSA::catchCurve(catch~agecap,data=sum_a,ages2use=-2,weighted=TRUE)\nsummary(cc1b)\n```\n\n::: {.cell-output .cell-output-stdout}\n```{.output}\n#R|      Estimate Std. Error t value  Pr(>|t|)\n#R|  Z  0.6105809  0.1688334 3.61647 0.0152761\n#R|  A 45.6964676         NA      NA        NA\n```\n:::\n:::\n\n\nI am not sure what is the best way to handle this problem, but this exercise suggests to me that the published mortality estimate should be considered cautiously.\n\n&nbsp;\n\n\n::: {.cell layout-align=\"center\"}\n\n:::",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}